import { GetStaticProps } from 'next';
import Head from 'next/head';
import React, { useState } from 'react';
import { Button } from '../components';
import { Htag } from '../components';
import { P } from '../components/P/P';
import { Rating } from '../components/Rating/Rating';
import { Tag } from '../components/Tag/Tag';
import { withLayout } from '../layout/Layout';
import axios from 'axios';
import { MenuItem } from '../interfaces/menu.inteface';

function Home({ menu }: HomeProps): JSX.Element {
  const [rating, setRating] = useState<number>(4);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Htag tag='h1'>
          Текст
        </Htag>
        <Button appearance='primary' arrow='right'>Кнопка</Button>
        <Button appearance='ghost' arrow='down'>Подробнее</Button>
        <P fontSize='s'>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Incidunt, ipsam aut quibusdam fugiat tempora vero labore quasi dolor sit expedita, omnis magni exercitationem quos. Sequi sunt ad excepturi mollitia, vel quae aut facilis dicta nemo dignissimos. Quisquam architecto doloribus praesentium.
        </P>
        <Tag color={'green'}>1000rub</Tag>
        <Tag color={'primary'}>Начало</Tag>
        <Tag color={'red'}>hh.ru</Tag>
        <Tag color={'gray'}>01</Tag>
        <Tag color={'ghost'}>что</Tag>
        <Rating rating={rating} isEditable setRating={setRating} />
        <ul>
          {menu.map(m => (<li key={m._id.secondCategory}>{m._id.secondCategory}</li>))}
        </ul>
        
      </main>
    </>
  );
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<MenuItem[]>(process.env.NEXT_PUBLIC_DOMAIN + '/api/top-page/find', {
    firstCategory
  });
  return {
    props: {
      menu,
      firstCategory
    }
  };
};

interface HomeProps extends Record<string, unknown> {
  menu: MenuItem[];
  firstCategory: number;
}