import Head from 'next/head';
import React from 'react';
import { Button } from '../components';
import { Htag } from '../components';
import P from '../components/P/P';
import Rating from '../components/Rating/Rating';
import Tag from '../components/Tag/Tag';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Htag tag='h1'>
          Текст
        </Htag>
        <Button appearance='primary' arrow='right'>Кнопка</Button>
        <Button appearance='ghost' arrow='down'>Подробнее</Button>
        <P fontSize='s'>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Incidunt, ipsam aut quibusdam fugiat tempora vero labore quasi dolor sit expedita, omnis magni exercitationem quos. Sequi sunt ad excepturi mollitia, vel quae aut facilis dicta nemo dignissimos. Quisquam architecto doloribus praesentium.
        </P>
        <Tag color={'green'}>1000rub</Tag>
        <Tag color={'primary'}>Начало</Tag>
        <Tag color={'red'}>hh.ru</Tag>
        <Tag color={'gray'}>01</Tag>
        <Tag color={'ghost'}>что</Tag>
        <Rating />
      </main>
    </>
  );
}
